[package]
name = "wadump"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
wa = { path = "../../wa" }
prost = "^0.6"
keyring = "^0.9"
rpassword = "^4"
base64 = "^0.12"
argh = "^0.1"